TEMPLATES = {
    "fastapi": {
        "structure": [
            "app/",
            "app/main.py",
            "app/routes/",
            "app/models/",
            "app/schemas/",
            "requirements.txt",
            "README.md"
        ],
        "files_content": {
            "app/main.py": """from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Hello, FastAPI!"}
""",
            "requirements.txt": "fastapi\nuvicorn\n",
            "README.md": "# FastAPI Project\nGenerated by Project Template Generator\n"
        }
    }
}
